CREATE TABLE IF NOT EXISTS JOB (
    JOB_ID INT AUTO_INCREMENT PRIMARY KEY,
    POSTED_DATE DATE NOT NULL,
    DEPARTMENT VARCHAR(255) NOT NULL,
    JOB_TITLE VARCHAR(255) NOT NULL,
    JOB_DESCRIPTIONS TEXT NOT NULL,
    SALARY_RANGE VARCHAR(255) NOT NULL,
    LOCATION VARCHAR(255) NOT NULL,
    PRIORITY ENUM('High', 'Medium', 'Low') NOT NULL,
    STATUS ENUM('Open', 'Closed', 'Offer-Sent') NOT NULL
);

CREATE TABLE IF NOT EXISTS RECRUITER (
    RECRUITER_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PHONE VARCHAR(255) UNIQUE NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS Candidates (
    candidate_id INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    phone VARCHAR(20),
    resume_link VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Application (
    application_id INT AUTO_INCREMENT PRIMARY KEY,
    application_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    application_status ENUM('Applied','Interviewing','Hired','Rejected') NOT NULL,
    notes TEXT NOT NULL,
    candidate_id INT NOT NULL,
    job_id INT NOT NULL,
    FOREIGN KEY (job_id) REFERENCES JOB(JOB_ID),
    FOREIGN KEY (candidate_id) REFERENCES Candidates(candidate_id)
);
